-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	button_fill = "rbxassetid://6037473336",
	collapse_down = "rbxassetid://6037473412",
	collapse_right = "rbxassetid://6037473464",
	hamburger = "rbxassetid://6037473573",
	preview = "rbxassetid://6037473638",
}
