name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - uses: osyrisrblx/setup-rojo@v1
        with:
          version: 0.6.0-alpha.1
      - name: Build
        run: rojo build plugin.project.json --output plugin.rbxmx
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: plugin
          path: plugin.rbxmx